export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USERS_REQUEST = "USERS_REQUEST";
export const USERS_SUCCESS = "USERS_SUCCESS";
export const USERS_FAIL = "USERS_FAIL";

export const PRODUCTS_REQUEST = "PRODUCTS_REQUEST";
export const PRODUCTS_SUCCESS = "PRODUCTS_SUCCESS";
export const PRODUCTS_FAIL = "PRODUCTS_FAIL";

export const PRODUCT_ADD_REQUEST = "PRODUCT_ADD_REQUEST";
export const PRODUCT_ADD_SUCCESS = "PRODUCT_ADD_SUCCESS";
export const PRODUCT_ADD_FAIL = "PRODUCT_ADD_FAIL";

export const INSIGHTS_REQUEST = "INSIGHTS_REQUEST";
export const INSIGHTS_SUCCESS = "INSIGHTS_SUCCESS";
export const INSIGHTS_FAIL = "INSIGHTS_FAIL";

export const REVIEWS_REQUEST = "REVIEWS_REQUEST";
export const REVIEWS_SUCCESS = "REVIEWS_SUCCESS";
export const REVIEWS_FAIL = "REVIEWS_FAIL";

export const SUPPORT_REQUEST = "SUPPORT_REQUEST";
export const SUPPORT_SUCCESS = "SUPPORT_SUCCESS";
export const SUPPORT_FAIL = "SUPPORT_FAIL";

export const ORDERS_REQUEST = "ORDERS_REQUEST";
export const ORDERS_SUCCESS = "ORDERS_SUCCESS";
export const ORDERS_FAIL = "ORDERS_FAIL";

export const USER_LOGOUT = "USER_LOGOUT";

export const REMOVE_ERROR = "REMOVE_ERROR";
